### PR TITLE
Add support for subscription expiration time namespace settings

### LINKED ISSUE #1253: Add namespaces subscriptionExpirationTime commands
**Is your feature request related to a problem? Please describe.**
I would like to get / set / delete a namespace's [subscriptionExpiration policies](https://github.com/apache/pulsar/blob/d7e8ea16e6682df9a9354cda25cf4f1f9cb54429/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java#L494-L559) using the go client. It is not currently implemented

**Describe the solution you'd like**
In [pulsaradmin/pkg/admin/namespace.go](https://github.com/apache/pulsar-client-go/blob/master/pulsaradmin/pkg/admin/namespace.go), implement `GetSubscriptionExpirationTime`, `SetSubscriptionExpirationTime`, `RemoveSubscriptionExpirationTime`.

**Describe alternatives you've considered**
Not sure

**Additional context**
Ultimately I would like to add these to the streamnative [terraform-provider](https://github.com/streamnative/terraform-provider-pulsar). This is an intermediary step.

### PR DESCRIPTION
**Pull request by klevy-toast**
Fixes #1253 

### Motivation

Adds support for the get / set / delete `subscriptionExpirationTime` namespace settings.

### Modifications

Created new functions in `namespace.go` that implement support for `subscriptionExpirationTime` settings

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

  - *Added integration tests for new client functions*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API: (**yes** / no)
  - The schema: (yes / **no** / don't know)
  - The default values of configurations: (yes / **no**)
  - The wire protocol: (yes / **no**)

### Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / **GoDocs** / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by RobertIndie — APPROVED** [review]
LGTM. Please fix the conflict

**Comment by klevy-toast** [comment]
Thanks for the review @RobertIndie , I have fixed the merge conflicts

**Comment by RobertIndie** [comment]
Please take a look at this compilation error: https://github.com/apache/pulsar-client-go/actions/runs/10045685387/job/27779892242?pr=1254#step:5:30
```
  Error: pulsaradmin/pkg/admin/namespace_test.go:234:11: undefined: admin
```
@klevy-toast

**Comment by RobertIndie** [comment]
There are still some lint issues. If you are using macos or linux, you can run [`make lint`](https://github.com/apache/pulsar-client-go/blob/c3b0633a2f5fcc5b560b504d04fdef0e82f6b72a/Makefile#L35-L36) to check locally.

**Comment by klevy-toast** [comment]
@RobertIndie thanks, fixed.

Is there a way for me to run the build independently? It's a bit annoying that I cannot see what issues are failing the build until a maintainer triggers it.

**Comment by RobertIndie** [comment]
> Is there a way for me to run the build independently? It's a bit annoying that I cannot see what issues are failing the build until a maintainer triggers it.

You can run `make build` to build it locally. To check for CI failures, you can open a pull request in your own repository. This allows you to review any CI issues directly.

**Comment by klevy-toast** [comment]
> > Is there a way for me to run the build independently? It's a bit annoying that I cannot see what issues are failing the build until a maintainer triggers it.
> 
> You can run `make build` to build it locally. To check for CI failures, you can open a pull request in your own repository. This allows you to review any CI issues directly.

That's great info, can it be added to the [contributing guide](https://github.com/apache/pulsar-client-go/blob/master/CONTRIBUTING.md)?
